// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
	sessionio "github.com/kyh0703/portfoilo-media/internal/core/usecase/sessionio"
)

type FakeCreateSessionUsecase struct {
	CreateSessionStub        func(context.Context, sessionio.CreateSessionRequest) (sessionio.CreateSessionResponse, error)
	createSessionMutex       sync.RWMutex
	createSessionArgsForCall []struct {
		arg1 context.Context
		arg2 sessionio.CreateSessionRequest
	}
	createSessionReturns struct {
		result1 sessionio.CreateSessionResponse
		result2 error
	}
	createSessionReturnsOnCall map[int]struct {
		result1 sessionio.CreateSessionResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCreateSessionUsecase) CreateSession(arg1 context.Context, arg2 sessionio.CreateSessionRequest) (sessionio.CreateSessionResponse, error) {
	fake.createSessionMutex.Lock()
	ret, specificReturn := fake.createSessionReturnsOnCall[len(fake.createSessionArgsForCall)]
	fake.createSessionArgsForCall = append(fake.createSessionArgsForCall, struct {
		arg1 context.Context
		arg2 sessionio.CreateSessionRequest
	}{arg1, arg2})
	stub := fake.CreateSessionStub
	fakeReturns := fake.createSessionReturns
	fake.recordInvocation("CreateSession", []interface{}{arg1, arg2})
	fake.createSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCreateSessionUsecase) CreateSessionCallCount() int {
	fake.createSessionMutex.RLock()
	defer fake.createSessionMutex.RUnlock()
	return len(fake.createSessionArgsForCall)
}

func (fake *FakeCreateSessionUsecase) CreateSessionCalls(stub func(context.Context, sessionio.CreateSessionRequest) (sessionio.CreateSessionResponse, error)) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = stub
}

func (fake *FakeCreateSessionUsecase) CreateSessionArgsForCall(i int) (context.Context, sessionio.CreateSessionRequest) {
	fake.createSessionMutex.RLock()
	defer fake.createSessionMutex.RUnlock()
	argsForCall := fake.createSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCreateSessionUsecase) CreateSessionReturns(result1 sessionio.CreateSessionResponse, result2 error) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = nil
	fake.createSessionReturns = struct {
		result1 sessionio.CreateSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeCreateSessionUsecase) CreateSessionReturnsOnCall(i int, result1 sessionio.CreateSessionResponse, result2 error) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = nil
	if fake.createSessionReturnsOnCall == nil {
		fake.createSessionReturnsOnCall = make(map[int]struct {
			result1 sessionio.CreateSessionResponse
			result2 error
		})
	}
	fake.createSessionReturnsOnCall[i] = struct {
		result1 sessionio.CreateSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeCreateSessionUsecase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCreateSessionUsecase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.CreateSessionUsecase = new(FakeCreateSessionUsecase)
