// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/dto/session"
	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
)

type FakeSessionUsecase struct {
	AcceptOfferStub        func(context.Context, session.AcceptOfferRequest) (session.AcceptOfferResponse, error)
	acceptOfferMutex       sync.RWMutex
	acceptOfferArgsForCall []struct {
		arg1 context.Context
		arg2 session.AcceptOfferRequest
	}
	acceptOfferReturns struct {
		result1 session.AcceptOfferResponse
		result2 error
	}
	acceptOfferReturnsOnCall map[int]struct {
		result1 session.AcceptOfferResponse
		result2 error
	}
	CreateSessionStub        func(context.Context, session.CreateSessionRequest) (session.CreateSessionResponse, error)
	createSessionMutex       sync.RWMutex
	createSessionArgsForCall []struct {
		arg1 context.Context
		arg2 session.CreateSessionRequest
	}
	createSessionReturns struct {
		result1 session.CreateSessionResponse
		result2 error
	}
	createSessionReturnsOnCall map[int]struct {
		result1 session.CreateSessionResponse
		result2 error
	}
	EndSessionStub        func(context.Context, session.EndSessionRequest) (session.EndSessionResponse, error)
	endSessionMutex       sync.RWMutex
	endSessionArgsForCall []struct {
		arg1 context.Context
		arg2 session.EndSessionRequest
	}
	endSessionReturns struct {
		result1 session.EndSessionResponse
		result2 error
	}
	endSessionReturnsOnCall map[int]struct {
		result1 session.EndSessionResponse
		result2 error
	}
	GetHealthStub        func(context.Context) error
	getHealthMutex       sync.RWMutex
	getHealthArgsForCall []struct {
		arg1 context.Context
	}
	getHealthReturns struct {
		result1 error
	}
	getHealthReturnsOnCall map[int]struct {
		result1 error
	}
	GetRuntimeStatsStub        func(context.Context) (session.RuntimeStatsResponse, error)
	getRuntimeStatsMutex       sync.RWMutex
	getRuntimeStatsArgsForCall []struct {
		arg1 context.Context
	}
	getRuntimeStatsReturns struct {
		result1 session.RuntimeStatsResponse
		result2 error
	}
	getRuntimeStatsReturnsOnCall map[int]struct {
		result1 session.RuntimeStatsResponse
		result2 error
	}
	GetSessionStatusStub        func(context.Context, session.GetSessionStatusRequest) (session.GetSessionStatusResponse, bool, error)
	getSessionStatusMutex       sync.RWMutex
	getSessionStatusArgsForCall []struct {
		arg1 context.Context
		arg2 session.GetSessionStatusRequest
	}
	getSessionStatusReturns struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}
	getSessionStatusReturnsOnCall map[int]struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}
	LeaveParticipantStub        func(context.Context, session.LeaveParticipantRequest) (session.LeaveParticipantResponse, error)
	leaveParticipantMutex       sync.RWMutex
	leaveParticipantArgsForCall []struct {
		arg1 context.Context
		arg2 session.LeaveParticipantRequest
	}
	leaveParticipantReturns struct {
		result1 session.LeaveParticipantResponse
		result2 error
	}
	leaveParticipantReturnsOnCall map[int]struct {
		result1 session.LeaveParticipantResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSessionUsecase) AcceptOffer(arg1 context.Context, arg2 session.AcceptOfferRequest) (session.AcceptOfferResponse, error) {
	fake.acceptOfferMutex.Lock()
	ret, specificReturn := fake.acceptOfferReturnsOnCall[len(fake.acceptOfferArgsForCall)]
	fake.acceptOfferArgsForCall = append(fake.acceptOfferArgsForCall, struct {
		arg1 context.Context
		arg2 session.AcceptOfferRequest
	}{arg1, arg2})
	stub := fake.AcceptOfferStub
	fakeReturns := fake.acceptOfferReturns
	fake.recordInvocation("AcceptOffer", []interface{}{arg1, arg2})
	fake.acceptOfferMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionUsecase) AcceptOfferCallCount() int {
	fake.acceptOfferMutex.RLock()
	defer fake.acceptOfferMutex.RUnlock()
	return len(fake.acceptOfferArgsForCall)
}

func (fake *FakeSessionUsecase) AcceptOfferCalls(stub func(context.Context, session.AcceptOfferRequest) (session.AcceptOfferResponse, error)) {
	fake.acceptOfferMutex.Lock()
	defer fake.acceptOfferMutex.Unlock()
	fake.AcceptOfferStub = stub
}

func (fake *FakeSessionUsecase) AcceptOfferArgsForCall(i int) (context.Context, session.AcceptOfferRequest) {
	fake.acceptOfferMutex.RLock()
	defer fake.acceptOfferMutex.RUnlock()
	argsForCall := fake.acceptOfferArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionUsecase) AcceptOfferReturns(result1 session.AcceptOfferResponse, result2 error) {
	fake.acceptOfferMutex.Lock()
	defer fake.acceptOfferMutex.Unlock()
	fake.AcceptOfferStub = nil
	fake.acceptOfferReturns = struct {
		result1 session.AcceptOfferResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) AcceptOfferReturnsOnCall(i int, result1 session.AcceptOfferResponse, result2 error) {
	fake.acceptOfferMutex.Lock()
	defer fake.acceptOfferMutex.Unlock()
	fake.AcceptOfferStub = nil
	if fake.acceptOfferReturnsOnCall == nil {
		fake.acceptOfferReturnsOnCall = make(map[int]struct {
			result1 session.AcceptOfferResponse
			result2 error
		})
	}
	fake.acceptOfferReturnsOnCall[i] = struct {
		result1 session.AcceptOfferResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) CreateSession(arg1 context.Context, arg2 session.CreateSessionRequest) (session.CreateSessionResponse, error) {
	fake.createSessionMutex.Lock()
	ret, specificReturn := fake.createSessionReturnsOnCall[len(fake.createSessionArgsForCall)]
	fake.createSessionArgsForCall = append(fake.createSessionArgsForCall, struct {
		arg1 context.Context
		arg2 session.CreateSessionRequest
	}{arg1, arg2})
	stub := fake.CreateSessionStub
	fakeReturns := fake.createSessionReturns
	fake.recordInvocation("CreateSession", []interface{}{arg1, arg2})
	fake.createSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionUsecase) CreateSessionCallCount() int {
	fake.createSessionMutex.RLock()
	defer fake.createSessionMutex.RUnlock()
	return len(fake.createSessionArgsForCall)
}

func (fake *FakeSessionUsecase) CreateSessionCalls(stub func(context.Context, session.CreateSessionRequest) (session.CreateSessionResponse, error)) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = stub
}

func (fake *FakeSessionUsecase) CreateSessionArgsForCall(i int) (context.Context, session.CreateSessionRequest) {
	fake.createSessionMutex.RLock()
	defer fake.createSessionMutex.RUnlock()
	argsForCall := fake.createSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionUsecase) CreateSessionReturns(result1 session.CreateSessionResponse, result2 error) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = nil
	fake.createSessionReturns = struct {
		result1 session.CreateSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) CreateSessionReturnsOnCall(i int, result1 session.CreateSessionResponse, result2 error) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = nil
	if fake.createSessionReturnsOnCall == nil {
		fake.createSessionReturnsOnCall = make(map[int]struct {
			result1 session.CreateSessionResponse
			result2 error
		})
	}
	fake.createSessionReturnsOnCall[i] = struct {
		result1 session.CreateSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) EndSession(arg1 context.Context, arg2 session.EndSessionRequest) (session.EndSessionResponse, error) {
	fake.endSessionMutex.Lock()
	ret, specificReturn := fake.endSessionReturnsOnCall[len(fake.endSessionArgsForCall)]
	fake.endSessionArgsForCall = append(fake.endSessionArgsForCall, struct {
		arg1 context.Context
		arg2 session.EndSessionRequest
	}{arg1, arg2})
	stub := fake.EndSessionStub
	fakeReturns := fake.endSessionReturns
	fake.recordInvocation("EndSession", []interface{}{arg1, arg2})
	fake.endSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionUsecase) EndSessionCallCount() int {
	fake.endSessionMutex.RLock()
	defer fake.endSessionMutex.RUnlock()
	return len(fake.endSessionArgsForCall)
}

func (fake *FakeSessionUsecase) EndSessionCalls(stub func(context.Context, session.EndSessionRequest) (session.EndSessionResponse, error)) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = stub
}

func (fake *FakeSessionUsecase) EndSessionArgsForCall(i int) (context.Context, session.EndSessionRequest) {
	fake.endSessionMutex.RLock()
	defer fake.endSessionMutex.RUnlock()
	argsForCall := fake.endSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionUsecase) EndSessionReturns(result1 session.EndSessionResponse, result2 error) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = nil
	fake.endSessionReturns = struct {
		result1 session.EndSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) EndSessionReturnsOnCall(i int, result1 session.EndSessionResponse, result2 error) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = nil
	if fake.endSessionReturnsOnCall == nil {
		fake.endSessionReturnsOnCall = make(map[int]struct {
			result1 session.EndSessionResponse
			result2 error
		})
	}
	fake.endSessionReturnsOnCall[i] = struct {
		result1 session.EndSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) GetHealth(arg1 context.Context) error {
	fake.getHealthMutex.Lock()
	ret, specificReturn := fake.getHealthReturnsOnCall[len(fake.getHealthArgsForCall)]
	fake.getHealthArgsForCall = append(fake.getHealthArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetHealthStub
	fakeReturns := fake.getHealthReturns
	fake.recordInvocation("GetHealth", []interface{}{arg1})
	fake.getHealthMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSessionUsecase) GetHealthCallCount() int {
	fake.getHealthMutex.RLock()
	defer fake.getHealthMutex.RUnlock()
	return len(fake.getHealthArgsForCall)
}

func (fake *FakeSessionUsecase) GetHealthCalls(stub func(context.Context) error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = stub
}

func (fake *FakeSessionUsecase) GetHealthArgsForCall(i int) context.Context {
	fake.getHealthMutex.RLock()
	defer fake.getHealthMutex.RUnlock()
	argsForCall := fake.getHealthArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSessionUsecase) GetHealthReturns(result1 error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = nil
	fake.getHealthReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionUsecase) GetHealthReturnsOnCall(i int, result1 error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = nil
	if fake.getHealthReturnsOnCall == nil {
		fake.getHealthReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getHealthReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionUsecase) GetRuntimeStats(arg1 context.Context) (session.RuntimeStatsResponse, error) {
	fake.getRuntimeStatsMutex.Lock()
	ret, specificReturn := fake.getRuntimeStatsReturnsOnCall[len(fake.getRuntimeStatsArgsForCall)]
	fake.getRuntimeStatsArgsForCall = append(fake.getRuntimeStatsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetRuntimeStatsStub
	fakeReturns := fake.getRuntimeStatsReturns
	fake.recordInvocation("GetRuntimeStats", []interface{}{arg1})
	fake.getRuntimeStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionUsecase) GetRuntimeStatsCallCount() int {
	fake.getRuntimeStatsMutex.RLock()
	defer fake.getRuntimeStatsMutex.RUnlock()
	return len(fake.getRuntimeStatsArgsForCall)
}

func (fake *FakeSessionUsecase) GetRuntimeStatsCalls(stub func(context.Context) (session.RuntimeStatsResponse, error)) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = stub
}

func (fake *FakeSessionUsecase) GetRuntimeStatsArgsForCall(i int) context.Context {
	fake.getRuntimeStatsMutex.RLock()
	defer fake.getRuntimeStatsMutex.RUnlock()
	argsForCall := fake.getRuntimeStatsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSessionUsecase) GetRuntimeStatsReturns(result1 session.RuntimeStatsResponse, result2 error) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = nil
	fake.getRuntimeStatsReturns = struct {
		result1 session.RuntimeStatsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) GetRuntimeStatsReturnsOnCall(i int, result1 session.RuntimeStatsResponse, result2 error) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = nil
	if fake.getRuntimeStatsReturnsOnCall == nil {
		fake.getRuntimeStatsReturnsOnCall = make(map[int]struct {
			result1 session.RuntimeStatsResponse
			result2 error
		})
	}
	fake.getRuntimeStatsReturnsOnCall[i] = struct {
		result1 session.RuntimeStatsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) GetSessionStatus(arg1 context.Context, arg2 session.GetSessionStatusRequest) (session.GetSessionStatusResponse, bool, error) {
	fake.getSessionStatusMutex.Lock()
	ret, specificReturn := fake.getSessionStatusReturnsOnCall[len(fake.getSessionStatusArgsForCall)]
	fake.getSessionStatusArgsForCall = append(fake.getSessionStatusArgsForCall, struct {
		arg1 context.Context
		arg2 session.GetSessionStatusRequest
	}{arg1, arg2})
	stub := fake.GetSessionStatusStub
	fakeReturns := fake.getSessionStatusReturns
	fake.recordInvocation("GetSessionStatus", []interface{}{arg1, arg2})
	fake.getSessionStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeSessionUsecase) GetSessionStatusCallCount() int {
	fake.getSessionStatusMutex.RLock()
	defer fake.getSessionStatusMutex.RUnlock()
	return len(fake.getSessionStatusArgsForCall)
}

func (fake *FakeSessionUsecase) GetSessionStatusCalls(stub func(context.Context, session.GetSessionStatusRequest) (session.GetSessionStatusResponse, bool, error)) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = stub
}

func (fake *FakeSessionUsecase) GetSessionStatusArgsForCall(i int) (context.Context, session.GetSessionStatusRequest) {
	fake.getSessionStatusMutex.RLock()
	defer fake.getSessionStatusMutex.RUnlock()
	argsForCall := fake.getSessionStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionUsecase) GetSessionStatusReturns(result1 session.GetSessionStatusResponse, result2 bool, result3 error) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = nil
	fake.getSessionStatusReturns = struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSessionUsecase) GetSessionStatusReturnsOnCall(i int, result1 session.GetSessionStatusResponse, result2 bool, result3 error) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = nil
	if fake.getSessionStatusReturnsOnCall == nil {
		fake.getSessionStatusReturnsOnCall = make(map[int]struct {
			result1 session.GetSessionStatusResponse
			result2 bool
			result3 error
		})
	}
	fake.getSessionStatusReturnsOnCall[i] = struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSessionUsecase) LeaveParticipant(arg1 context.Context, arg2 session.LeaveParticipantRequest) (session.LeaveParticipantResponse, error) {
	fake.leaveParticipantMutex.Lock()
	ret, specificReturn := fake.leaveParticipantReturnsOnCall[len(fake.leaveParticipantArgsForCall)]
	fake.leaveParticipantArgsForCall = append(fake.leaveParticipantArgsForCall, struct {
		arg1 context.Context
		arg2 session.LeaveParticipantRequest
	}{arg1, arg2})
	stub := fake.LeaveParticipantStub
	fakeReturns := fake.leaveParticipantReturns
	fake.recordInvocation("LeaveParticipant", []interface{}{arg1, arg2})
	fake.leaveParticipantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionUsecase) LeaveParticipantCallCount() int {
	fake.leaveParticipantMutex.RLock()
	defer fake.leaveParticipantMutex.RUnlock()
	return len(fake.leaveParticipantArgsForCall)
}

func (fake *FakeSessionUsecase) LeaveParticipantCalls(stub func(context.Context, session.LeaveParticipantRequest) (session.LeaveParticipantResponse, error)) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = stub
}

func (fake *FakeSessionUsecase) LeaveParticipantArgsForCall(i int) (context.Context, session.LeaveParticipantRequest) {
	fake.leaveParticipantMutex.RLock()
	defer fake.leaveParticipantMutex.RUnlock()
	argsForCall := fake.leaveParticipantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionUsecase) LeaveParticipantReturns(result1 session.LeaveParticipantResponse, result2 error) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = nil
	fake.leaveParticipantReturns = struct {
		result1 session.LeaveParticipantResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) LeaveParticipantReturnsOnCall(i int, result1 session.LeaveParticipantResponse, result2 error) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = nil
	if fake.leaveParticipantReturnsOnCall == nil {
		fake.leaveParticipantReturnsOnCall = make(map[int]struct {
			result1 session.LeaveParticipantResponse
			result2 error
		})
	}
	fake.leaveParticipantReturnsOnCall[i] = struct {
		result1 session.LeaveParticipantResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionUsecase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSessionUsecase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.SessionUsecase = new(FakeSessionUsecase)
