// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/dto/session"
	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
)

type FakeEndSessionUsecase struct {
	EndSessionStub        func(context.Context, session.EndSessionRequest) (session.EndSessionResponse, error)
	endSessionMutex       sync.RWMutex
	endSessionArgsForCall []struct {
		arg1 context.Context
		arg2 session.EndSessionRequest
	}
	endSessionReturns struct {
		result1 session.EndSessionResponse
		result2 error
	}
	endSessionReturnsOnCall map[int]struct {
		result1 session.EndSessionResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEndSessionUsecase) EndSession(arg1 context.Context, arg2 session.EndSessionRequest) (session.EndSessionResponse, error) {
	fake.endSessionMutex.Lock()
	ret, specificReturn := fake.endSessionReturnsOnCall[len(fake.endSessionArgsForCall)]
	fake.endSessionArgsForCall = append(fake.endSessionArgsForCall, struct {
		arg1 context.Context
		arg2 session.EndSessionRequest
	}{arg1, arg2})
	stub := fake.EndSessionStub
	fakeReturns := fake.endSessionReturns
	fake.recordInvocation("EndSession", []interface{}{arg1, arg2})
	fake.endSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeEndSessionUsecase) EndSessionCallCount() int {
	fake.endSessionMutex.RLock()
	defer fake.endSessionMutex.RUnlock()
	return len(fake.endSessionArgsForCall)
}

func (fake *FakeEndSessionUsecase) EndSessionCalls(stub func(context.Context, session.EndSessionRequest) (session.EndSessionResponse, error)) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = stub
}

func (fake *FakeEndSessionUsecase) EndSessionArgsForCall(i int) (context.Context, session.EndSessionRequest) {
	fake.endSessionMutex.RLock()
	defer fake.endSessionMutex.RUnlock()
	argsForCall := fake.endSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEndSessionUsecase) EndSessionReturns(result1 session.EndSessionResponse, result2 error) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = nil
	fake.endSessionReturns = struct {
		result1 session.EndSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeEndSessionUsecase) EndSessionReturnsOnCall(i int, result1 session.EndSessionResponse, result2 error) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = nil
	if fake.endSessionReturnsOnCall == nil {
		fake.endSessionReturnsOnCall = make(map[int]struct {
			result1 session.EndSessionResponse
			result2 error
		})
	}
	fake.endSessionReturnsOnCall[i] = struct {
		result1 session.EndSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeEndSessionUsecase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEndSessionUsecase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.EndSessionUsecase = new(FakeEndSessionUsecase)
