// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
	sessionio "github.com/kyh0703/portfoilo-media/internal/core/usecase/sessionio"
)

type FakeGetRuntimeStatsQuery struct {
	GetRuntimeStatsStub        func(context.Context) (sessionio.RuntimeStatsResponse, error)
	getRuntimeStatsMutex       sync.RWMutex
	getRuntimeStatsArgsForCall []struct {
		arg1 context.Context
	}
	getRuntimeStatsReturns struct {
		result1 sessionio.RuntimeStatsResponse
		result2 error
	}
	getRuntimeStatsReturnsOnCall map[int]struct {
		result1 sessionio.RuntimeStatsResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetRuntimeStatsQuery) GetRuntimeStats(arg1 context.Context) (sessionio.RuntimeStatsResponse, error) {
	fake.getRuntimeStatsMutex.Lock()
	ret, specificReturn := fake.getRuntimeStatsReturnsOnCall[len(fake.getRuntimeStatsArgsForCall)]
	fake.getRuntimeStatsArgsForCall = append(fake.getRuntimeStatsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetRuntimeStatsStub
	fakeReturns := fake.getRuntimeStatsReturns
	fake.recordInvocation("GetRuntimeStats", []interface{}{arg1})
	fake.getRuntimeStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGetRuntimeStatsQuery) GetRuntimeStatsCallCount() int {
	fake.getRuntimeStatsMutex.RLock()
	defer fake.getRuntimeStatsMutex.RUnlock()
	return len(fake.getRuntimeStatsArgsForCall)
}

func (fake *FakeGetRuntimeStatsQuery) GetRuntimeStatsCalls(stub func(context.Context) (sessionio.RuntimeStatsResponse, error)) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = stub
}

func (fake *FakeGetRuntimeStatsQuery) GetRuntimeStatsArgsForCall(i int) context.Context {
	fake.getRuntimeStatsMutex.RLock()
	defer fake.getRuntimeStatsMutex.RUnlock()
	argsForCall := fake.getRuntimeStatsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGetRuntimeStatsQuery) GetRuntimeStatsReturns(result1 sessionio.RuntimeStatsResponse, result2 error) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = nil
	fake.getRuntimeStatsReturns = struct {
		result1 sessionio.RuntimeStatsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGetRuntimeStatsQuery) GetRuntimeStatsReturnsOnCall(i int, result1 sessionio.RuntimeStatsResponse, result2 error) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = nil
	if fake.getRuntimeStatsReturnsOnCall == nil {
		fake.getRuntimeStatsReturnsOnCall = make(map[int]struct {
			result1 sessionio.RuntimeStatsResponse
			result2 error
		})
	}
	fake.getRuntimeStatsReturnsOnCall[i] = struct {
		result1 sessionio.RuntimeStatsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGetRuntimeStatsQuery) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetRuntimeStatsQuery) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.GetRuntimeStatsQuery = new(FakeGetRuntimeStatsQuery)
