// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
)

type FakeGetHealthQuery struct {
	GetHealthStub        func(context.Context) error
	getHealthMutex       sync.RWMutex
	getHealthArgsForCall []struct {
		arg1 context.Context
	}
	getHealthReturns struct {
		result1 error
	}
	getHealthReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetHealthQuery) GetHealth(arg1 context.Context) error {
	fake.getHealthMutex.Lock()
	ret, specificReturn := fake.getHealthReturnsOnCall[len(fake.getHealthArgsForCall)]
	fake.getHealthArgsForCall = append(fake.getHealthArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetHealthStub
	fakeReturns := fake.getHealthReturns
	fake.recordInvocation("GetHealth", []interface{}{arg1})
	fake.getHealthMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetHealthQuery) GetHealthCallCount() int {
	fake.getHealthMutex.RLock()
	defer fake.getHealthMutex.RUnlock()
	return len(fake.getHealthArgsForCall)
}

func (fake *FakeGetHealthQuery) GetHealthCalls(stub func(context.Context) error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = stub
}

func (fake *FakeGetHealthQuery) GetHealthArgsForCall(i int) context.Context {
	fake.getHealthMutex.RLock()
	defer fake.getHealthMutex.RUnlock()
	argsForCall := fake.getHealthArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGetHealthQuery) GetHealthReturns(result1 error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = nil
	fake.getHealthReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGetHealthQuery) GetHealthReturnsOnCall(i int, result1 error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = nil
	if fake.getHealthReturnsOnCall == nil {
		fake.getHealthReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getHealthReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGetHealthQuery) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetHealthQuery) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.GetHealthQuery = new(FakeGetHealthQuery)
