// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
	sessionio "github.com/kyh0703/portfoilo-media/internal/core/usecase/sessionio"
)

type FakeJoinSessionUsecase struct {
	JoinSessionStub        func(context.Context, sessionio.JoinSessionCommand) (sessionio.JoinSessionResult, error)
	joinSessionMutex       sync.RWMutex
	joinSessionArgsForCall []struct {
		arg1 context.Context
		arg2 sessionio.JoinSessionCommand
	}
	joinSessionReturns struct {
		result1 sessionio.JoinSessionResult
		result2 error
	}
	joinSessionReturnsOnCall map[int]struct {
		result1 sessionio.JoinSessionResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJoinSessionUsecase) JoinSession(arg1 context.Context, arg2 sessionio.JoinSessionCommand) (sessionio.JoinSessionResult, error) {
	fake.joinSessionMutex.Lock()
	ret, specificReturn := fake.joinSessionReturnsOnCall[len(fake.joinSessionArgsForCall)]
	fake.joinSessionArgsForCall = append(fake.joinSessionArgsForCall, struct {
		arg1 context.Context
		arg2 sessionio.JoinSessionCommand
	}{arg1, arg2})
	stub := fake.JoinSessionStub
	fakeReturns := fake.joinSessionReturns
	fake.recordInvocation("JoinSession", []interface{}{arg1, arg2})
	fake.joinSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJoinSessionUsecase) JoinSessionCallCount() int {
	fake.joinSessionMutex.RLock()
	defer fake.joinSessionMutex.RUnlock()
	return len(fake.joinSessionArgsForCall)
}

func (fake *FakeJoinSessionUsecase) JoinSessionCalls(stub func(context.Context, sessionio.JoinSessionCommand) (sessionio.JoinSessionResult, error)) {
	fake.joinSessionMutex.Lock()
	defer fake.joinSessionMutex.Unlock()
	fake.JoinSessionStub = stub
}

func (fake *FakeJoinSessionUsecase) JoinSessionArgsForCall(i int) (context.Context, sessionio.JoinSessionCommand) {
	fake.joinSessionMutex.RLock()
	defer fake.joinSessionMutex.RUnlock()
	argsForCall := fake.joinSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJoinSessionUsecase) JoinSessionReturns(result1 sessionio.JoinSessionResult, result2 error) {
	fake.joinSessionMutex.Lock()
	defer fake.joinSessionMutex.Unlock()
	fake.JoinSessionStub = nil
	fake.joinSessionReturns = struct {
		result1 sessionio.JoinSessionResult
		result2 error
	}{result1, result2}
}

func (fake *FakeJoinSessionUsecase) JoinSessionReturnsOnCall(i int, result1 sessionio.JoinSessionResult, result2 error) {
	fake.joinSessionMutex.Lock()
	defer fake.joinSessionMutex.Unlock()
	fake.JoinSessionStub = nil
	if fake.joinSessionReturnsOnCall == nil {
		fake.joinSessionReturnsOnCall = make(map[int]struct {
			result1 sessionio.JoinSessionResult
			result2 error
		})
	}
	fake.joinSessionReturnsOnCall[i] = struct {
		result1 sessionio.JoinSessionResult
		result2 error
	}{result1, result2}
}

func (fake *FakeJoinSessionUsecase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJoinSessionUsecase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.JoinSessionUsecase = new(FakeJoinSessionUsecase)
