// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/dto/session"
	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
)

type FakeGetSessionStatusQuery struct {
	GetSessionStatusStub        func(context.Context, session.GetSessionStatusRequest) (session.GetSessionStatusResponse, bool, error)
	getSessionStatusMutex       sync.RWMutex
	getSessionStatusArgsForCall []struct {
		arg1 context.Context
		arg2 session.GetSessionStatusRequest
	}
	getSessionStatusReturns struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}
	getSessionStatusReturnsOnCall map[int]struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetSessionStatusQuery) GetSessionStatus(arg1 context.Context, arg2 session.GetSessionStatusRequest) (session.GetSessionStatusResponse, bool, error) {
	fake.getSessionStatusMutex.Lock()
	ret, specificReturn := fake.getSessionStatusReturnsOnCall[len(fake.getSessionStatusArgsForCall)]
	fake.getSessionStatusArgsForCall = append(fake.getSessionStatusArgsForCall, struct {
		arg1 context.Context
		arg2 session.GetSessionStatusRequest
	}{arg1, arg2})
	stub := fake.GetSessionStatusStub
	fakeReturns := fake.getSessionStatusReturns
	fake.recordInvocation("GetSessionStatus", []interface{}{arg1, arg2})
	fake.getSessionStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeGetSessionStatusQuery) GetSessionStatusCallCount() int {
	fake.getSessionStatusMutex.RLock()
	defer fake.getSessionStatusMutex.RUnlock()
	return len(fake.getSessionStatusArgsForCall)
}

func (fake *FakeGetSessionStatusQuery) GetSessionStatusCalls(stub func(context.Context, session.GetSessionStatusRequest) (session.GetSessionStatusResponse, bool, error)) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = stub
}

func (fake *FakeGetSessionStatusQuery) GetSessionStatusArgsForCall(i int) (context.Context, session.GetSessionStatusRequest) {
	fake.getSessionStatusMutex.RLock()
	defer fake.getSessionStatusMutex.RUnlock()
	argsForCall := fake.getSessionStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGetSessionStatusQuery) GetSessionStatusReturns(result1 session.GetSessionStatusResponse, result2 bool, result3 error) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = nil
	fake.getSessionStatusReturns = struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeGetSessionStatusQuery) GetSessionStatusReturnsOnCall(i int, result1 session.GetSessionStatusResponse, result2 bool, result3 error) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = nil
	if fake.getSessionStatusReturnsOnCall == nil {
		fake.getSessionStatusReturnsOnCall = make(map[int]struct {
			result1 session.GetSessionStatusResponse
			result2 bool
			result3 error
		})
	}
	fake.getSessionStatusReturnsOnCall[i] = struct {
		result1 session.GetSessionStatusResponse
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeGetSessionStatusQuery) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetSessionStatusQuery) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.GetSessionStatusQuery = new(FakeGetSessionStatusQuery)
