// Code generated by counterfeiter. DO NOT EDIT.
package usecasefakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/usecase"
	sessionio "github.com/kyh0703/portfoilo-media/internal/core/usecase/sessionio"
)

type FakeLeaveParticipantUsecase struct {
	LeaveParticipantStub        func(context.Context, sessionio.LeaveParticipantRequest) (sessionio.LeaveParticipantResponse, error)
	leaveParticipantMutex       sync.RWMutex
	leaveParticipantArgsForCall []struct {
		arg1 context.Context
		arg2 sessionio.LeaveParticipantRequest
	}
	leaveParticipantReturns struct {
		result1 sessionio.LeaveParticipantResponse
		result2 error
	}
	leaveParticipantReturnsOnCall map[int]struct {
		result1 sessionio.LeaveParticipantResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLeaveParticipantUsecase) LeaveParticipant(arg1 context.Context, arg2 sessionio.LeaveParticipantRequest) (sessionio.LeaveParticipantResponse, error) {
	fake.leaveParticipantMutex.Lock()
	ret, specificReturn := fake.leaveParticipantReturnsOnCall[len(fake.leaveParticipantArgsForCall)]
	fake.leaveParticipantArgsForCall = append(fake.leaveParticipantArgsForCall, struct {
		arg1 context.Context
		arg2 sessionio.LeaveParticipantRequest
	}{arg1, arg2})
	stub := fake.LeaveParticipantStub
	fakeReturns := fake.leaveParticipantReturns
	fake.recordInvocation("LeaveParticipant", []interface{}{arg1, arg2})
	fake.leaveParticipantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLeaveParticipantUsecase) LeaveParticipantCallCount() int {
	fake.leaveParticipantMutex.RLock()
	defer fake.leaveParticipantMutex.RUnlock()
	return len(fake.leaveParticipantArgsForCall)
}

func (fake *FakeLeaveParticipantUsecase) LeaveParticipantCalls(stub func(context.Context, sessionio.LeaveParticipantRequest) (sessionio.LeaveParticipantResponse, error)) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = stub
}

func (fake *FakeLeaveParticipantUsecase) LeaveParticipantArgsForCall(i int) (context.Context, sessionio.LeaveParticipantRequest) {
	fake.leaveParticipantMutex.RLock()
	defer fake.leaveParticipantMutex.RUnlock()
	argsForCall := fake.leaveParticipantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeLeaveParticipantUsecase) LeaveParticipantReturns(result1 sessionio.LeaveParticipantResponse, result2 error) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = nil
	fake.leaveParticipantReturns = struct {
		result1 sessionio.LeaveParticipantResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeLeaveParticipantUsecase) LeaveParticipantReturnsOnCall(i int, result1 sessionio.LeaveParticipantResponse, result2 error) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = nil
	if fake.leaveParticipantReturnsOnCall == nil {
		fake.leaveParticipantReturnsOnCall = make(map[int]struct {
			result1 sessionio.LeaveParticipantResponse
			result2 error
		})
	}
	fake.leaveParticipantReturnsOnCall[i] = struct {
		result1 sessionio.LeaveParticipantResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeLeaveParticipantUsecase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLeaveParticipantUsecase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecase.LeaveParticipantUsecase = new(FakeLeaveParticipantUsecase)
