root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/portfoilo-media ./cmd/app"
bin = "./tmp/portfoilo-media"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["tmp", "bin", ".git", ".worktrees"]
exclude_regex = ["_test.go"]
delay = 1000
stop_on_error = true

[log]
time = true
