// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/domain/entity"
	"github.com/kyh0703/portfoilo-media/internal/core/domain/repository"
)

type FakeMediaServerStateRepository struct {
	SaveStub        func(context.Context, entity.MediaServerState) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 context.Context
		arg2 entity.MediaServerState
	}
	saveReturns struct {
		result1 error
	}
	saveReturnsOnCall map[int]struct {
		result1 error
	}
	SaveOfflineStub        func(context.Context, entity.MediaServerState) error
	saveOfflineMutex       sync.RWMutex
	saveOfflineArgsForCall []struct {
		arg1 context.Context
		arg2 entity.MediaServerState
	}
	saveOfflineReturns struct {
		result1 error
	}
	saveOfflineReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMediaServerStateRepository) Save(arg1 context.Context, arg2 entity.MediaServerState) error {
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 context.Context
		arg2 entity.MediaServerState
	}{arg1, arg2})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1, arg2})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMediaServerStateRepository) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeMediaServerStateRepository) SaveCalls(stub func(context.Context, entity.MediaServerState) error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *FakeMediaServerStateRepository) SaveArgsForCall(i int) (context.Context, entity.MediaServerState) {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMediaServerStateRepository) SaveReturns(result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaServerStateRepository) SaveReturnsOnCall(i int, result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaServerStateRepository) SaveOffline(arg1 context.Context, arg2 entity.MediaServerState) error {
	fake.saveOfflineMutex.Lock()
	ret, specificReturn := fake.saveOfflineReturnsOnCall[len(fake.saveOfflineArgsForCall)]
	fake.saveOfflineArgsForCall = append(fake.saveOfflineArgsForCall, struct {
		arg1 context.Context
		arg2 entity.MediaServerState
	}{arg1, arg2})
	stub := fake.SaveOfflineStub
	fakeReturns := fake.saveOfflineReturns
	fake.recordInvocation("SaveOffline", []interface{}{arg1, arg2})
	fake.saveOfflineMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMediaServerStateRepository) SaveOfflineCallCount() int {
	fake.saveOfflineMutex.RLock()
	defer fake.saveOfflineMutex.RUnlock()
	return len(fake.saveOfflineArgsForCall)
}

func (fake *FakeMediaServerStateRepository) SaveOfflineCalls(stub func(context.Context, entity.MediaServerState) error) {
	fake.saveOfflineMutex.Lock()
	defer fake.saveOfflineMutex.Unlock()
	fake.SaveOfflineStub = stub
}

func (fake *FakeMediaServerStateRepository) SaveOfflineArgsForCall(i int) (context.Context, entity.MediaServerState) {
	fake.saveOfflineMutex.RLock()
	defer fake.saveOfflineMutex.RUnlock()
	argsForCall := fake.saveOfflineArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMediaServerStateRepository) SaveOfflineReturns(result1 error) {
	fake.saveOfflineMutex.Lock()
	defer fake.saveOfflineMutex.Unlock()
	fake.SaveOfflineStub = nil
	fake.saveOfflineReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaServerStateRepository) SaveOfflineReturnsOnCall(i int, result1 error) {
	fake.saveOfflineMutex.Lock()
	defer fake.saveOfflineMutex.Unlock()
	fake.SaveOfflineStub = nil
	if fake.saveOfflineReturnsOnCall == nil {
		fake.saveOfflineReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveOfflineReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaServerStateRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMediaServerStateRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.MediaServerStateRepository = new(FakeMediaServerStateRepository)
