// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/domain/entity"
	"github.com/kyh0703/portfoilo-media/internal/core/domain/repository"
	"github.com/kyh0703/portfoilo-media/internal/core/domain/vo"
)

type FakeMediaSessionStateRepository struct {
	DeleteStub        func(context.Context, vo.SessionID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 vo.SessionID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	FindBySessionIDStub        func(context.Context, vo.SessionID) (entity.MediaSessionState, bool, error)
	findBySessionIDMutex       sync.RWMutex
	findBySessionIDArgsForCall []struct {
		arg1 context.Context
		arg2 vo.SessionID
	}
	findBySessionIDReturns struct {
		result1 entity.MediaSessionState
		result2 bool
		result3 error
	}
	findBySessionIDReturnsOnCall map[int]struct {
		result1 entity.MediaSessionState
		result2 bool
		result3 error
	}
	SaveStub        func(context.Context, entity.MediaSessionState) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 context.Context
		arg2 entity.MediaSessionState
	}
	saveReturns struct {
		result1 error
	}
	saveReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMediaSessionStateRepository) Delete(arg1 context.Context, arg2 vo.SessionID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 vo.SessionID
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMediaSessionStateRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeMediaSessionStateRepository) DeleteCalls(stub func(context.Context, vo.SessionID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeMediaSessionStateRepository) DeleteArgsForCall(i int) (context.Context, vo.SessionID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMediaSessionStateRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaSessionStateRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaSessionStateRepository) FindBySessionID(arg1 context.Context, arg2 vo.SessionID) (entity.MediaSessionState, bool, error) {
	fake.findBySessionIDMutex.Lock()
	ret, specificReturn := fake.findBySessionIDReturnsOnCall[len(fake.findBySessionIDArgsForCall)]
	fake.findBySessionIDArgsForCall = append(fake.findBySessionIDArgsForCall, struct {
		arg1 context.Context
		arg2 vo.SessionID
	}{arg1, arg2})
	stub := fake.FindBySessionIDStub
	fakeReturns := fake.findBySessionIDReturns
	fake.recordInvocation("FindBySessionID", []interface{}{arg1, arg2})
	fake.findBySessionIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeMediaSessionStateRepository) FindBySessionIDCallCount() int {
	fake.findBySessionIDMutex.RLock()
	defer fake.findBySessionIDMutex.RUnlock()
	return len(fake.findBySessionIDArgsForCall)
}

func (fake *FakeMediaSessionStateRepository) FindBySessionIDCalls(stub func(context.Context, vo.SessionID) (entity.MediaSessionState, bool, error)) {
	fake.findBySessionIDMutex.Lock()
	defer fake.findBySessionIDMutex.Unlock()
	fake.FindBySessionIDStub = stub
}

func (fake *FakeMediaSessionStateRepository) FindBySessionIDArgsForCall(i int) (context.Context, vo.SessionID) {
	fake.findBySessionIDMutex.RLock()
	defer fake.findBySessionIDMutex.RUnlock()
	argsForCall := fake.findBySessionIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMediaSessionStateRepository) FindBySessionIDReturns(result1 entity.MediaSessionState, result2 bool, result3 error) {
	fake.findBySessionIDMutex.Lock()
	defer fake.findBySessionIDMutex.Unlock()
	fake.FindBySessionIDStub = nil
	fake.findBySessionIDReturns = struct {
		result1 entity.MediaSessionState
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMediaSessionStateRepository) FindBySessionIDReturnsOnCall(i int, result1 entity.MediaSessionState, result2 bool, result3 error) {
	fake.findBySessionIDMutex.Lock()
	defer fake.findBySessionIDMutex.Unlock()
	fake.FindBySessionIDStub = nil
	if fake.findBySessionIDReturnsOnCall == nil {
		fake.findBySessionIDReturnsOnCall = make(map[int]struct {
			result1 entity.MediaSessionState
			result2 bool
			result3 error
		})
	}
	fake.findBySessionIDReturnsOnCall[i] = struct {
		result1 entity.MediaSessionState
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMediaSessionStateRepository) Save(arg1 context.Context, arg2 entity.MediaSessionState) error {
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 context.Context
		arg2 entity.MediaSessionState
	}{arg1, arg2})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1, arg2})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMediaSessionStateRepository) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeMediaSessionStateRepository) SaveCalls(stub func(context.Context, entity.MediaSessionState) error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *FakeMediaSessionStateRepository) SaveArgsForCall(i int) (context.Context, entity.MediaSessionState) {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMediaSessionStateRepository) SaveReturns(result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaSessionStateRepository) SaveReturnsOnCall(i int, result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMediaSessionStateRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMediaSessionStateRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.MediaSessionStateRepository = new(FakeMediaSessionStateRepository)
