// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/domain/entity"
	"github.com/kyh0703/portfoilo-media/internal/core/domain/repository"
	"github.com/kyh0703/portfoilo-media/internal/core/domain/vo"
)

type FakeRoomRuntimeRepository struct {
	DeleteStub        func(context.Context, vo.RoomID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 vo.RoomID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	FindBySessionIDStub        func(context.Context, vo.SessionID) (entity.Room, bool, error)
	findBySessionIDMutex       sync.RWMutex
	findBySessionIDArgsForCall []struct {
		arg1 context.Context
		arg2 vo.SessionID
	}
	findBySessionIDReturns struct {
		result1 entity.Room
		result2 bool
		result3 error
	}
	findBySessionIDReturnsOnCall map[int]struct {
		result1 entity.Room
		result2 bool
		result3 error
	}
	ListStub        func(context.Context) ([]entity.Room, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 context.Context
	}
	listReturns struct {
		result1 []entity.Room
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []entity.Room
		result2 error
	}
	SaveStub        func(context.Context, entity.Room) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 context.Context
		arg2 entity.Room
	}
	saveReturns struct {
		result1 error
	}
	saveReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRoomRuntimeRepository) Delete(arg1 context.Context, arg2 vo.RoomID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 vo.RoomID
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRoomRuntimeRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeRoomRuntimeRepository) DeleteCalls(stub func(context.Context, vo.RoomID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeRoomRuntimeRepository) DeleteArgsForCall(i int) (context.Context, vo.RoomID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRoomRuntimeRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRoomRuntimeRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRoomRuntimeRepository) FindBySessionID(arg1 context.Context, arg2 vo.SessionID) (entity.Room, bool, error) {
	fake.findBySessionIDMutex.Lock()
	ret, specificReturn := fake.findBySessionIDReturnsOnCall[len(fake.findBySessionIDArgsForCall)]
	fake.findBySessionIDArgsForCall = append(fake.findBySessionIDArgsForCall, struct {
		arg1 context.Context
		arg2 vo.SessionID
	}{arg1, arg2})
	stub := fake.FindBySessionIDStub
	fakeReturns := fake.findBySessionIDReturns
	fake.recordInvocation("FindBySessionID", []interface{}{arg1, arg2})
	fake.findBySessionIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeRoomRuntimeRepository) FindBySessionIDCallCount() int {
	fake.findBySessionIDMutex.RLock()
	defer fake.findBySessionIDMutex.RUnlock()
	return len(fake.findBySessionIDArgsForCall)
}

func (fake *FakeRoomRuntimeRepository) FindBySessionIDCalls(stub func(context.Context, vo.SessionID) (entity.Room, bool, error)) {
	fake.findBySessionIDMutex.Lock()
	defer fake.findBySessionIDMutex.Unlock()
	fake.FindBySessionIDStub = stub
}

func (fake *FakeRoomRuntimeRepository) FindBySessionIDArgsForCall(i int) (context.Context, vo.SessionID) {
	fake.findBySessionIDMutex.RLock()
	defer fake.findBySessionIDMutex.RUnlock()
	argsForCall := fake.findBySessionIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRoomRuntimeRepository) FindBySessionIDReturns(result1 entity.Room, result2 bool, result3 error) {
	fake.findBySessionIDMutex.Lock()
	defer fake.findBySessionIDMutex.Unlock()
	fake.FindBySessionIDStub = nil
	fake.findBySessionIDReturns = struct {
		result1 entity.Room
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeRoomRuntimeRepository) FindBySessionIDReturnsOnCall(i int, result1 entity.Room, result2 bool, result3 error) {
	fake.findBySessionIDMutex.Lock()
	defer fake.findBySessionIDMutex.Unlock()
	fake.FindBySessionIDStub = nil
	if fake.findBySessionIDReturnsOnCall == nil {
		fake.findBySessionIDReturnsOnCall = make(map[int]struct {
			result1 entity.Room
			result2 bool
			result3 error
		})
	}
	fake.findBySessionIDReturnsOnCall[i] = struct {
		result1 entity.Room
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeRoomRuntimeRepository) List(arg1 context.Context) ([]entity.Room, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRoomRuntimeRepository) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeRoomRuntimeRepository) ListCalls(stub func(context.Context) ([]entity.Room, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeRoomRuntimeRepository) ListArgsForCall(i int) context.Context {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRoomRuntimeRepository) ListReturns(result1 []entity.Room, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []entity.Room
		result2 error
	}{result1, result2}
}

func (fake *FakeRoomRuntimeRepository) ListReturnsOnCall(i int, result1 []entity.Room, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []entity.Room
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []entity.Room
		result2 error
	}{result1, result2}
}

func (fake *FakeRoomRuntimeRepository) Save(arg1 context.Context, arg2 entity.Room) error {
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 context.Context
		arg2 entity.Room
	}{arg1, arg2})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1, arg2})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRoomRuntimeRepository) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeRoomRuntimeRepository) SaveCalls(stub func(context.Context, entity.Room) error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *FakeRoomRuntimeRepository) SaveArgsForCall(i int) (context.Context, entity.Room) {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRoomRuntimeRepository) SaveReturns(result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRoomRuntimeRepository) SaveReturnsOnCall(i int, result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRoomRuntimeRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRoomRuntimeRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.RoomRuntimeRepository = new(FakeRoomRuntimeRepository)
