// Code generated by counterfeiter. DO NOT EDIT.
package openaifakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/pkg/openai"
)

type FakeRealtimeCallHanger struct {
	HangupCallStub        func(context.Context, string) error
	hangupCallMutex       sync.RWMutex
	hangupCallArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	hangupCallReturns struct {
		result1 error
	}
	hangupCallReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRealtimeCallHanger) HangupCall(arg1 context.Context, arg2 string) error {
	fake.hangupCallMutex.Lock()
	ret, specificReturn := fake.hangupCallReturnsOnCall[len(fake.hangupCallArgsForCall)]
	fake.hangupCallArgsForCall = append(fake.hangupCallArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.HangupCallStub
	fakeReturns := fake.hangupCallReturns
	fake.recordInvocation("HangupCall", []interface{}{arg1, arg2})
	fake.hangupCallMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRealtimeCallHanger) HangupCallCallCount() int {
	fake.hangupCallMutex.RLock()
	defer fake.hangupCallMutex.RUnlock()
	return len(fake.hangupCallArgsForCall)
}

func (fake *FakeRealtimeCallHanger) HangupCallCalls(stub func(context.Context, string) error) {
	fake.hangupCallMutex.Lock()
	defer fake.hangupCallMutex.Unlock()
	fake.HangupCallStub = stub
}

func (fake *FakeRealtimeCallHanger) HangupCallArgsForCall(i int) (context.Context, string) {
	fake.hangupCallMutex.RLock()
	defer fake.hangupCallMutex.RUnlock()
	argsForCall := fake.hangupCallArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRealtimeCallHanger) HangupCallReturns(result1 error) {
	fake.hangupCallMutex.Lock()
	defer fake.hangupCallMutex.Unlock()
	fake.HangupCallStub = nil
	fake.hangupCallReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealtimeCallHanger) HangupCallReturnsOnCall(i int, result1 error) {
	fake.hangupCallMutex.Lock()
	defer fake.hangupCallMutex.Unlock()
	fake.HangupCallStub = nil
	if fake.hangupCallReturnsOnCall == nil {
		fake.hangupCallReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.hangupCallReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealtimeCallHanger) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRealtimeCallHanger) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ openai.RealtimeCallHanger = new(FakeRealtimeCallHanger)
