// Code generated by counterfeiter. DO NOT EDIT.
package openaifakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/pkg/openai"
)

type FakeRealtimeCallManager struct {
	CreateCallStub        func(context.Context, openai.CreateCallInput) (openai.CreateCallResult, error)
	createCallMutex       sync.RWMutex
	createCallArgsForCall []struct {
		arg1 context.Context
		arg2 openai.CreateCallInput
	}
	createCallReturns struct {
		result1 openai.CreateCallResult
		result2 error
	}
	createCallReturnsOnCall map[int]struct {
		result1 openai.CreateCallResult
		result2 error
	}
	HangupCallStub        func(context.Context, string) error
	hangupCallMutex       sync.RWMutex
	hangupCallArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	hangupCallReturns struct {
		result1 error
	}
	hangupCallReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRealtimeCallManager) CreateCall(arg1 context.Context, arg2 openai.CreateCallInput) (openai.CreateCallResult, error) {
	fake.createCallMutex.Lock()
	ret, specificReturn := fake.createCallReturnsOnCall[len(fake.createCallArgsForCall)]
	fake.createCallArgsForCall = append(fake.createCallArgsForCall, struct {
		arg1 context.Context
		arg2 openai.CreateCallInput
	}{arg1, arg2})
	stub := fake.CreateCallStub
	fakeReturns := fake.createCallReturns
	fake.recordInvocation("CreateCall", []interface{}{arg1, arg2})
	fake.createCallMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRealtimeCallManager) CreateCallCallCount() int {
	fake.createCallMutex.RLock()
	defer fake.createCallMutex.RUnlock()
	return len(fake.createCallArgsForCall)
}

func (fake *FakeRealtimeCallManager) CreateCallCalls(stub func(context.Context, openai.CreateCallInput) (openai.CreateCallResult, error)) {
	fake.createCallMutex.Lock()
	defer fake.createCallMutex.Unlock()
	fake.CreateCallStub = stub
}

func (fake *FakeRealtimeCallManager) CreateCallArgsForCall(i int) (context.Context, openai.CreateCallInput) {
	fake.createCallMutex.RLock()
	defer fake.createCallMutex.RUnlock()
	argsForCall := fake.createCallArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRealtimeCallManager) CreateCallReturns(result1 openai.CreateCallResult, result2 error) {
	fake.createCallMutex.Lock()
	defer fake.createCallMutex.Unlock()
	fake.CreateCallStub = nil
	fake.createCallReturns = struct {
		result1 openai.CreateCallResult
		result2 error
	}{result1, result2}
}

func (fake *FakeRealtimeCallManager) CreateCallReturnsOnCall(i int, result1 openai.CreateCallResult, result2 error) {
	fake.createCallMutex.Lock()
	defer fake.createCallMutex.Unlock()
	fake.CreateCallStub = nil
	if fake.createCallReturnsOnCall == nil {
		fake.createCallReturnsOnCall = make(map[int]struct {
			result1 openai.CreateCallResult
			result2 error
		})
	}
	fake.createCallReturnsOnCall[i] = struct {
		result1 openai.CreateCallResult
		result2 error
	}{result1, result2}
}

func (fake *FakeRealtimeCallManager) HangupCall(arg1 context.Context, arg2 string) error {
	fake.hangupCallMutex.Lock()
	ret, specificReturn := fake.hangupCallReturnsOnCall[len(fake.hangupCallArgsForCall)]
	fake.hangupCallArgsForCall = append(fake.hangupCallArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.HangupCallStub
	fakeReturns := fake.hangupCallReturns
	fake.recordInvocation("HangupCall", []interface{}{arg1, arg2})
	fake.hangupCallMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRealtimeCallManager) HangupCallCallCount() int {
	fake.hangupCallMutex.RLock()
	defer fake.hangupCallMutex.RUnlock()
	return len(fake.hangupCallArgsForCall)
}

func (fake *FakeRealtimeCallManager) HangupCallCalls(stub func(context.Context, string) error) {
	fake.hangupCallMutex.Lock()
	defer fake.hangupCallMutex.Unlock()
	fake.HangupCallStub = stub
}

func (fake *FakeRealtimeCallManager) HangupCallArgsForCall(i int) (context.Context, string) {
	fake.hangupCallMutex.RLock()
	defer fake.hangupCallMutex.RUnlock()
	argsForCall := fake.hangupCallArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRealtimeCallManager) HangupCallReturns(result1 error) {
	fake.hangupCallMutex.Lock()
	defer fake.hangupCallMutex.Unlock()
	fake.HangupCallStub = nil
	fake.hangupCallReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealtimeCallManager) HangupCallReturnsOnCall(i int, result1 error) {
	fake.hangupCallMutex.Lock()
	defer fake.hangupCallMutex.Unlock()
	fake.HangupCallStub = nil
	if fake.hangupCallReturnsOnCall == nil {
		fake.hangupCallReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.hangupCallReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealtimeCallManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRealtimeCallManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ openai.RealtimeCallManager = new(FakeRealtimeCallManager)
