// Code generated by counterfeiter. DO NOT EDIT.
package sessionfakes

import (
	"context"
	"sync"
	"time"

	sessiona "github.com/kyh0703/portfoilo-media/internal/core/dto/session"
	"github.com/kyh0703/portfoilo-media/internal/core/service/session"
)

type FakeService struct {
	CleanupIdleRoomsStub        func(context.Context, time.Duration) (int, error)
	cleanupIdleRoomsMutex       sync.RWMutex
	cleanupIdleRoomsArgsForCall []struct {
		arg1 context.Context
		arg2 time.Duration
	}
	cleanupIdleRoomsReturns struct {
		result1 int
		result2 error
	}
	cleanupIdleRoomsReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	CreateSessionStub        func(context.Context, sessiona.CreateSessionRequest) (sessiona.CreateSessionResponse, error)
	createSessionMutex       sync.RWMutex
	createSessionArgsForCall []struct {
		arg1 context.Context
		arg2 sessiona.CreateSessionRequest
	}
	createSessionReturns struct {
		result1 sessiona.CreateSessionResponse
		result2 error
	}
	createSessionReturnsOnCall map[int]struct {
		result1 sessiona.CreateSessionResponse
		result2 error
	}
	EndSessionStub        func(context.Context, sessiona.EndSessionRequest) (sessiona.EndSessionResponse, error)
	endSessionMutex       sync.RWMutex
	endSessionArgsForCall []struct {
		arg1 context.Context
		arg2 sessiona.EndSessionRequest
	}
	endSessionReturns struct {
		result1 sessiona.EndSessionResponse
		result2 error
	}
	endSessionReturnsOnCall map[int]struct {
		result1 sessiona.EndSessionResponse
		result2 error
	}
	GetHealthStub        func(context.Context) error
	getHealthMutex       sync.RWMutex
	getHealthArgsForCall []struct {
		arg1 context.Context
	}
	getHealthReturns struct {
		result1 error
	}
	getHealthReturnsOnCall map[int]struct {
		result1 error
	}
	GetRuntimeStatsStub        func(context.Context) (sessiona.RuntimeStatsResponse, error)
	getRuntimeStatsMutex       sync.RWMutex
	getRuntimeStatsArgsForCall []struct {
		arg1 context.Context
	}
	getRuntimeStatsReturns struct {
		result1 sessiona.RuntimeStatsResponse
		result2 error
	}
	getRuntimeStatsReturnsOnCall map[int]struct {
		result1 sessiona.RuntimeStatsResponse
		result2 error
	}
	GetSessionStatusStub        func(context.Context, sessiona.GetSessionStatusRequest) (sessiona.GetSessionStatusResult, bool, error)
	getSessionStatusMutex       sync.RWMutex
	getSessionStatusArgsForCall []struct {
		arg1 context.Context
		arg2 sessiona.GetSessionStatusRequest
	}
	getSessionStatusReturns struct {
		result1 sessiona.GetSessionStatusResult
		result2 bool
		result3 error
	}
	getSessionStatusReturnsOnCall map[int]struct {
		result1 sessiona.GetSessionStatusResult
		result2 bool
		result3 error
	}
	JoinSessionStub        func(context.Context, sessiona.JoinSessionCommand) (sessiona.JoinSessionResult, error)
	joinSessionMutex       sync.RWMutex
	joinSessionArgsForCall []struct {
		arg1 context.Context
		arg2 sessiona.JoinSessionCommand
	}
	joinSessionReturns struct {
		result1 sessiona.JoinSessionResult
		result2 error
	}
	joinSessionReturnsOnCall map[int]struct {
		result1 sessiona.JoinSessionResult
		result2 error
	}
	LeaveParticipantStub        func(context.Context, sessiona.LeaveParticipantRequest) (sessiona.LeaveParticipantResponse, error)
	leaveParticipantMutex       sync.RWMutex
	leaveParticipantArgsForCall []struct {
		arg1 context.Context
		arg2 sessiona.LeaveParticipantRequest
	}
	leaveParticipantReturns struct {
		result1 sessiona.LeaveParticipantResponse
		result2 error
	}
	leaveParticipantReturnsOnCall map[int]struct {
		result1 sessiona.LeaveParticipantResponse
		result2 error
	}
	ShutdownActiveRoomsStub        func(context.Context) (int, error)
	shutdownActiveRoomsMutex       sync.RWMutex
	shutdownActiveRoomsArgsForCall []struct {
		arg1 context.Context
	}
	shutdownActiveRoomsReturns struct {
		result1 int
		result2 error
	}
	shutdownActiveRoomsReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) CleanupIdleRooms(arg1 context.Context, arg2 time.Duration) (int, error) {
	fake.cleanupIdleRoomsMutex.Lock()
	ret, specificReturn := fake.cleanupIdleRoomsReturnsOnCall[len(fake.cleanupIdleRoomsArgsForCall)]
	fake.cleanupIdleRoomsArgsForCall = append(fake.cleanupIdleRoomsArgsForCall, struct {
		arg1 context.Context
		arg2 time.Duration
	}{arg1, arg2})
	stub := fake.CleanupIdleRoomsStub
	fakeReturns := fake.cleanupIdleRoomsReturns
	fake.recordInvocation("CleanupIdleRooms", []interface{}{arg1, arg2})
	fake.cleanupIdleRoomsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CleanupIdleRoomsCallCount() int {
	fake.cleanupIdleRoomsMutex.RLock()
	defer fake.cleanupIdleRoomsMutex.RUnlock()
	return len(fake.cleanupIdleRoomsArgsForCall)
}

func (fake *FakeService) CleanupIdleRoomsCalls(stub func(context.Context, time.Duration) (int, error)) {
	fake.cleanupIdleRoomsMutex.Lock()
	defer fake.cleanupIdleRoomsMutex.Unlock()
	fake.CleanupIdleRoomsStub = stub
}

func (fake *FakeService) CleanupIdleRoomsArgsForCall(i int) (context.Context, time.Duration) {
	fake.cleanupIdleRoomsMutex.RLock()
	defer fake.cleanupIdleRoomsMutex.RUnlock()
	argsForCall := fake.cleanupIdleRoomsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) CleanupIdleRoomsReturns(result1 int, result2 error) {
	fake.cleanupIdleRoomsMutex.Lock()
	defer fake.cleanupIdleRoomsMutex.Unlock()
	fake.CleanupIdleRoomsStub = nil
	fake.cleanupIdleRoomsReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CleanupIdleRoomsReturnsOnCall(i int, result1 int, result2 error) {
	fake.cleanupIdleRoomsMutex.Lock()
	defer fake.cleanupIdleRoomsMutex.Unlock()
	fake.CleanupIdleRoomsStub = nil
	if fake.cleanupIdleRoomsReturnsOnCall == nil {
		fake.cleanupIdleRoomsReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.cleanupIdleRoomsReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateSession(arg1 context.Context, arg2 sessiona.CreateSessionRequest) (sessiona.CreateSessionResponse, error) {
	fake.createSessionMutex.Lock()
	ret, specificReturn := fake.createSessionReturnsOnCall[len(fake.createSessionArgsForCall)]
	fake.createSessionArgsForCall = append(fake.createSessionArgsForCall, struct {
		arg1 context.Context
		arg2 sessiona.CreateSessionRequest
	}{arg1, arg2})
	stub := fake.CreateSessionStub
	fakeReturns := fake.createSessionReturns
	fake.recordInvocation("CreateSession", []interface{}{arg1, arg2})
	fake.createSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreateSessionCallCount() int {
	fake.createSessionMutex.RLock()
	defer fake.createSessionMutex.RUnlock()
	return len(fake.createSessionArgsForCall)
}

func (fake *FakeService) CreateSessionCalls(stub func(context.Context, sessiona.CreateSessionRequest) (sessiona.CreateSessionResponse, error)) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = stub
}

func (fake *FakeService) CreateSessionArgsForCall(i int) (context.Context, sessiona.CreateSessionRequest) {
	fake.createSessionMutex.RLock()
	defer fake.createSessionMutex.RUnlock()
	argsForCall := fake.createSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) CreateSessionReturns(result1 sessiona.CreateSessionResponse, result2 error) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = nil
	fake.createSessionReturns = struct {
		result1 sessiona.CreateSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateSessionReturnsOnCall(i int, result1 sessiona.CreateSessionResponse, result2 error) {
	fake.createSessionMutex.Lock()
	defer fake.createSessionMutex.Unlock()
	fake.CreateSessionStub = nil
	if fake.createSessionReturnsOnCall == nil {
		fake.createSessionReturnsOnCall = make(map[int]struct {
			result1 sessiona.CreateSessionResponse
			result2 error
		})
	}
	fake.createSessionReturnsOnCall[i] = struct {
		result1 sessiona.CreateSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) EndSession(arg1 context.Context, arg2 sessiona.EndSessionRequest) (sessiona.EndSessionResponse, error) {
	fake.endSessionMutex.Lock()
	ret, specificReturn := fake.endSessionReturnsOnCall[len(fake.endSessionArgsForCall)]
	fake.endSessionArgsForCall = append(fake.endSessionArgsForCall, struct {
		arg1 context.Context
		arg2 sessiona.EndSessionRequest
	}{arg1, arg2})
	stub := fake.EndSessionStub
	fakeReturns := fake.endSessionReturns
	fake.recordInvocation("EndSession", []interface{}{arg1, arg2})
	fake.endSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) EndSessionCallCount() int {
	fake.endSessionMutex.RLock()
	defer fake.endSessionMutex.RUnlock()
	return len(fake.endSessionArgsForCall)
}

func (fake *FakeService) EndSessionCalls(stub func(context.Context, sessiona.EndSessionRequest) (sessiona.EndSessionResponse, error)) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = stub
}

func (fake *FakeService) EndSessionArgsForCall(i int) (context.Context, sessiona.EndSessionRequest) {
	fake.endSessionMutex.RLock()
	defer fake.endSessionMutex.RUnlock()
	argsForCall := fake.endSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) EndSessionReturns(result1 sessiona.EndSessionResponse, result2 error) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = nil
	fake.endSessionReturns = struct {
		result1 sessiona.EndSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) EndSessionReturnsOnCall(i int, result1 sessiona.EndSessionResponse, result2 error) {
	fake.endSessionMutex.Lock()
	defer fake.endSessionMutex.Unlock()
	fake.EndSessionStub = nil
	if fake.endSessionReturnsOnCall == nil {
		fake.endSessionReturnsOnCall = make(map[int]struct {
			result1 sessiona.EndSessionResponse
			result2 error
		})
	}
	fake.endSessionReturnsOnCall[i] = struct {
		result1 sessiona.EndSessionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetHealth(arg1 context.Context) error {
	fake.getHealthMutex.Lock()
	ret, specificReturn := fake.getHealthReturnsOnCall[len(fake.getHealthArgsForCall)]
	fake.getHealthArgsForCall = append(fake.getHealthArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetHealthStub
	fakeReturns := fake.getHealthReturns
	fake.recordInvocation("GetHealth", []interface{}{arg1})
	fake.getHealthMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) GetHealthCallCount() int {
	fake.getHealthMutex.RLock()
	defer fake.getHealthMutex.RUnlock()
	return len(fake.getHealthArgsForCall)
}

func (fake *FakeService) GetHealthCalls(stub func(context.Context) error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = stub
}

func (fake *FakeService) GetHealthArgsForCall(i int) context.Context {
	fake.getHealthMutex.RLock()
	defer fake.getHealthMutex.RUnlock()
	argsForCall := fake.getHealthArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) GetHealthReturns(result1 error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = nil
	fake.getHealthReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) GetHealthReturnsOnCall(i int, result1 error) {
	fake.getHealthMutex.Lock()
	defer fake.getHealthMutex.Unlock()
	fake.GetHealthStub = nil
	if fake.getHealthReturnsOnCall == nil {
		fake.getHealthReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getHealthReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) GetRuntimeStats(arg1 context.Context) (sessiona.RuntimeStatsResponse, error) {
	fake.getRuntimeStatsMutex.Lock()
	ret, specificReturn := fake.getRuntimeStatsReturnsOnCall[len(fake.getRuntimeStatsArgsForCall)]
	fake.getRuntimeStatsArgsForCall = append(fake.getRuntimeStatsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetRuntimeStatsStub
	fakeReturns := fake.getRuntimeStatsReturns
	fake.recordInvocation("GetRuntimeStats", []interface{}{arg1})
	fake.getRuntimeStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetRuntimeStatsCallCount() int {
	fake.getRuntimeStatsMutex.RLock()
	defer fake.getRuntimeStatsMutex.RUnlock()
	return len(fake.getRuntimeStatsArgsForCall)
}

func (fake *FakeService) GetRuntimeStatsCalls(stub func(context.Context) (sessiona.RuntimeStatsResponse, error)) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = stub
}

func (fake *FakeService) GetRuntimeStatsArgsForCall(i int) context.Context {
	fake.getRuntimeStatsMutex.RLock()
	defer fake.getRuntimeStatsMutex.RUnlock()
	argsForCall := fake.getRuntimeStatsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) GetRuntimeStatsReturns(result1 sessiona.RuntimeStatsResponse, result2 error) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = nil
	fake.getRuntimeStatsReturns = struct {
		result1 sessiona.RuntimeStatsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetRuntimeStatsReturnsOnCall(i int, result1 sessiona.RuntimeStatsResponse, result2 error) {
	fake.getRuntimeStatsMutex.Lock()
	defer fake.getRuntimeStatsMutex.Unlock()
	fake.GetRuntimeStatsStub = nil
	if fake.getRuntimeStatsReturnsOnCall == nil {
		fake.getRuntimeStatsReturnsOnCall = make(map[int]struct {
			result1 sessiona.RuntimeStatsResponse
			result2 error
		})
	}
	fake.getRuntimeStatsReturnsOnCall[i] = struct {
		result1 sessiona.RuntimeStatsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetSessionStatus(arg1 context.Context, arg2 sessiona.GetSessionStatusRequest) (sessiona.GetSessionStatusResult, bool, error) {
	fake.getSessionStatusMutex.Lock()
	ret, specificReturn := fake.getSessionStatusReturnsOnCall[len(fake.getSessionStatusArgsForCall)]
	fake.getSessionStatusArgsForCall = append(fake.getSessionStatusArgsForCall, struct {
		arg1 context.Context
		arg2 sessiona.GetSessionStatusRequest
	}{arg1, arg2})
	stub := fake.GetSessionStatusStub
	fakeReturns := fake.getSessionStatusReturns
	fake.recordInvocation("GetSessionStatus", []interface{}{arg1, arg2})
	fake.getSessionStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeService) GetSessionStatusCallCount() int {
	fake.getSessionStatusMutex.RLock()
	defer fake.getSessionStatusMutex.RUnlock()
	return len(fake.getSessionStatusArgsForCall)
}

func (fake *FakeService) GetSessionStatusCalls(stub func(context.Context, sessiona.GetSessionStatusRequest) (sessiona.GetSessionStatusResult, bool, error)) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = stub
}

func (fake *FakeService) GetSessionStatusArgsForCall(i int) (context.Context, sessiona.GetSessionStatusRequest) {
	fake.getSessionStatusMutex.RLock()
	defer fake.getSessionStatusMutex.RUnlock()
	argsForCall := fake.getSessionStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetSessionStatusReturns(result1 sessiona.GetSessionStatusResult, result2 bool, result3 error) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = nil
	fake.getSessionStatusReturns = struct {
		result1 sessiona.GetSessionStatusResult
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeService) GetSessionStatusReturnsOnCall(i int, result1 sessiona.GetSessionStatusResult, result2 bool, result3 error) {
	fake.getSessionStatusMutex.Lock()
	defer fake.getSessionStatusMutex.Unlock()
	fake.GetSessionStatusStub = nil
	if fake.getSessionStatusReturnsOnCall == nil {
		fake.getSessionStatusReturnsOnCall = make(map[int]struct {
			result1 sessiona.GetSessionStatusResult
			result2 bool
			result3 error
		})
	}
	fake.getSessionStatusReturnsOnCall[i] = struct {
		result1 sessiona.GetSessionStatusResult
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeService) JoinSession(arg1 context.Context, arg2 sessiona.JoinSessionCommand) (sessiona.JoinSessionResult, error) {
	fake.joinSessionMutex.Lock()
	ret, specificReturn := fake.joinSessionReturnsOnCall[len(fake.joinSessionArgsForCall)]
	fake.joinSessionArgsForCall = append(fake.joinSessionArgsForCall, struct {
		arg1 context.Context
		arg2 sessiona.JoinSessionCommand
	}{arg1, arg2})
	stub := fake.JoinSessionStub
	fakeReturns := fake.joinSessionReturns
	fake.recordInvocation("JoinSession", []interface{}{arg1, arg2})
	fake.joinSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) JoinSessionCallCount() int {
	fake.joinSessionMutex.RLock()
	defer fake.joinSessionMutex.RUnlock()
	return len(fake.joinSessionArgsForCall)
}

func (fake *FakeService) JoinSessionCalls(stub func(context.Context, sessiona.JoinSessionCommand) (sessiona.JoinSessionResult, error)) {
	fake.joinSessionMutex.Lock()
	defer fake.joinSessionMutex.Unlock()
	fake.JoinSessionStub = stub
}

func (fake *FakeService) JoinSessionArgsForCall(i int) (context.Context, sessiona.JoinSessionCommand) {
	fake.joinSessionMutex.RLock()
	defer fake.joinSessionMutex.RUnlock()
	argsForCall := fake.joinSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) JoinSessionReturns(result1 sessiona.JoinSessionResult, result2 error) {
	fake.joinSessionMutex.Lock()
	defer fake.joinSessionMutex.Unlock()
	fake.JoinSessionStub = nil
	fake.joinSessionReturns = struct {
		result1 sessiona.JoinSessionResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JoinSessionReturnsOnCall(i int, result1 sessiona.JoinSessionResult, result2 error) {
	fake.joinSessionMutex.Lock()
	defer fake.joinSessionMutex.Unlock()
	fake.JoinSessionStub = nil
	if fake.joinSessionReturnsOnCall == nil {
		fake.joinSessionReturnsOnCall = make(map[int]struct {
			result1 sessiona.JoinSessionResult
			result2 error
		})
	}
	fake.joinSessionReturnsOnCall[i] = struct {
		result1 sessiona.JoinSessionResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) LeaveParticipant(arg1 context.Context, arg2 sessiona.LeaveParticipantRequest) (sessiona.LeaveParticipantResponse, error) {
	fake.leaveParticipantMutex.Lock()
	ret, specificReturn := fake.leaveParticipantReturnsOnCall[len(fake.leaveParticipantArgsForCall)]
	fake.leaveParticipantArgsForCall = append(fake.leaveParticipantArgsForCall, struct {
		arg1 context.Context
		arg2 sessiona.LeaveParticipantRequest
	}{arg1, arg2})
	stub := fake.LeaveParticipantStub
	fakeReturns := fake.leaveParticipantReturns
	fake.recordInvocation("LeaveParticipant", []interface{}{arg1, arg2})
	fake.leaveParticipantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) LeaveParticipantCallCount() int {
	fake.leaveParticipantMutex.RLock()
	defer fake.leaveParticipantMutex.RUnlock()
	return len(fake.leaveParticipantArgsForCall)
}

func (fake *FakeService) LeaveParticipantCalls(stub func(context.Context, sessiona.LeaveParticipantRequest) (sessiona.LeaveParticipantResponse, error)) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = stub
}

func (fake *FakeService) LeaveParticipantArgsForCall(i int) (context.Context, sessiona.LeaveParticipantRequest) {
	fake.leaveParticipantMutex.RLock()
	defer fake.leaveParticipantMutex.RUnlock()
	argsForCall := fake.leaveParticipantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) LeaveParticipantReturns(result1 sessiona.LeaveParticipantResponse, result2 error) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = nil
	fake.leaveParticipantReturns = struct {
		result1 sessiona.LeaveParticipantResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) LeaveParticipantReturnsOnCall(i int, result1 sessiona.LeaveParticipantResponse, result2 error) {
	fake.leaveParticipantMutex.Lock()
	defer fake.leaveParticipantMutex.Unlock()
	fake.LeaveParticipantStub = nil
	if fake.leaveParticipantReturnsOnCall == nil {
		fake.leaveParticipantReturnsOnCall = make(map[int]struct {
			result1 sessiona.LeaveParticipantResponse
			result2 error
		})
	}
	fake.leaveParticipantReturnsOnCall[i] = struct {
		result1 sessiona.LeaveParticipantResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ShutdownActiveRooms(arg1 context.Context) (int, error) {
	fake.shutdownActiveRoomsMutex.Lock()
	ret, specificReturn := fake.shutdownActiveRoomsReturnsOnCall[len(fake.shutdownActiveRoomsArgsForCall)]
	fake.shutdownActiveRoomsArgsForCall = append(fake.shutdownActiveRoomsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ShutdownActiveRoomsStub
	fakeReturns := fake.shutdownActiveRoomsReturns
	fake.recordInvocation("ShutdownActiveRooms", []interface{}{arg1})
	fake.shutdownActiveRoomsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ShutdownActiveRoomsCallCount() int {
	fake.shutdownActiveRoomsMutex.RLock()
	defer fake.shutdownActiveRoomsMutex.RUnlock()
	return len(fake.shutdownActiveRoomsArgsForCall)
}

func (fake *FakeService) ShutdownActiveRoomsCalls(stub func(context.Context) (int, error)) {
	fake.shutdownActiveRoomsMutex.Lock()
	defer fake.shutdownActiveRoomsMutex.Unlock()
	fake.ShutdownActiveRoomsStub = stub
}

func (fake *FakeService) ShutdownActiveRoomsArgsForCall(i int) context.Context {
	fake.shutdownActiveRoomsMutex.RLock()
	defer fake.shutdownActiveRoomsMutex.RUnlock()
	argsForCall := fake.shutdownActiveRoomsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ShutdownActiveRoomsReturns(result1 int, result2 error) {
	fake.shutdownActiveRoomsMutex.Lock()
	defer fake.shutdownActiveRoomsMutex.Unlock()
	fake.ShutdownActiveRoomsStub = nil
	fake.shutdownActiveRoomsReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ShutdownActiveRoomsReturnsOnCall(i int, result1 int, result2 error) {
	fake.shutdownActiveRoomsMutex.Lock()
	defer fake.shutdownActiveRoomsMutex.Unlock()
	fake.ShutdownActiveRoomsStub = nil
	if fake.shutdownActiveRoomsReturnsOnCall == nil {
		fake.shutdownActiveRoomsReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.shutdownActiveRoomsReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ session.Service = new(FakeService)
