// Code generated by counterfeiter. DO NOT EDIT.
package webrtcfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/core/domain/vo"
	"github.com/kyh0703/portfoilo-media/internal/pkg/webrtc"
)

type FakePeerConnectionFactory struct {
	AcceptOfferStub        func(context.Context, webrtc.OfferInput) (*webrtc.Peer, error)
	acceptOfferMutex       sync.RWMutex
	acceptOfferArgsForCall []struct {
		arg1 context.Context
		arg2 webrtc.OfferInput
	}
	acceptOfferReturns struct {
		result1 *webrtc.Peer
		result2 error
	}
	acceptOfferReturnsOnCall map[int]struct {
		result1 *webrtc.Peer
		result2 error
	}
	ApplyAnswerStub        func(context.Context, *webrtc.PeerOffer, string) (*webrtc.Peer, error)
	applyAnswerMutex       sync.RWMutex
	applyAnswerArgsForCall []struct {
		arg1 context.Context
		arg2 *webrtc.PeerOffer
		arg3 string
	}
	applyAnswerReturns struct {
		result1 *webrtc.Peer
		result2 error
	}
	applyAnswerReturnsOnCall map[int]struct {
		result1 *webrtc.Peer
		result2 error
	}
	CloseParticipantStub        func(context.Context, vo.SessionID, vo.ParticipantID) error
	closeParticipantMutex       sync.RWMutex
	closeParticipantArgsForCall []struct {
		arg1 context.Context
		arg2 vo.SessionID
		arg3 vo.ParticipantID
	}
	closeParticipantReturns struct {
		result1 error
	}
	closeParticipantReturnsOnCall map[int]struct {
		result1 error
	}
	CloseSessionStub        func(context.Context, vo.SessionID) error
	closeSessionMutex       sync.RWMutex
	closeSessionArgsForCall []struct {
		arg1 context.Context
		arg2 vo.SessionID
	}
	closeSessionReturns struct {
		result1 error
	}
	closeSessionReturnsOnCall map[int]struct {
		result1 error
	}
	CreateOfferStub        func(context.Context, webrtc.CreateOfferInput) (*webrtc.PeerOffer, error)
	createOfferMutex       sync.RWMutex
	createOfferArgsForCall []struct {
		arg1 context.Context
		arg2 webrtc.CreateOfferInput
	}
	createOfferReturns struct {
		result1 *webrtc.PeerOffer
		result2 error
	}
	createOfferReturnsOnCall map[int]struct {
		result1 *webrtc.PeerOffer
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePeerConnectionFactory) AcceptOffer(arg1 context.Context, arg2 webrtc.OfferInput) (*webrtc.Peer, error) {
	fake.acceptOfferMutex.Lock()
	ret, specificReturn := fake.acceptOfferReturnsOnCall[len(fake.acceptOfferArgsForCall)]
	fake.acceptOfferArgsForCall = append(fake.acceptOfferArgsForCall, struct {
		arg1 context.Context
		arg2 webrtc.OfferInput
	}{arg1, arg2})
	stub := fake.AcceptOfferStub
	fakeReturns := fake.acceptOfferReturns
	fake.recordInvocation("AcceptOffer", []interface{}{arg1, arg2})
	fake.acceptOfferMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePeerConnectionFactory) AcceptOfferCallCount() int {
	fake.acceptOfferMutex.RLock()
	defer fake.acceptOfferMutex.RUnlock()
	return len(fake.acceptOfferArgsForCall)
}

func (fake *FakePeerConnectionFactory) AcceptOfferCalls(stub func(context.Context, webrtc.OfferInput) (*webrtc.Peer, error)) {
	fake.acceptOfferMutex.Lock()
	defer fake.acceptOfferMutex.Unlock()
	fake.AcceptOfferStub = stub
}

func (fake *FakePeerConnectionFactory) AcceptOfferArgsForCall(i int) (context.Context, webrtc.OfferInput) {
	fake.acceptOfferMutex.RLock()
	defer fake.acceptOfferMutex.RUnlock()
	argsForCall := fake.acceptOfferArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePeerConnectionFactory) AcceptOfferReturns(result1 *webrtc.Peer, result2 error) {
	fake.acceptOfferMutex.Lock()
	defer fake.acceptOfferMutex.Unlock()
	fake.AcceptOfferStub = nil
	fake.acceptOfferReturns = struct {
		result1 *webrtc.Peer
		result2 error
	}{result1, result2}
}

func (fake *FakePeerConnectionFactory) AcceptOfferReturnsOnCall(i int, result1 *webrtc.Peer, result2 error) {
	fake.acceptOfferMutex.Lock()
	defer fake.acceptOfferMutex.Unlock()
	fake.AcceptOfferStub = nil
	if fake.acceptOfferReturnsOnCall == nil {
		fake.acceptOfferReturnsOnCall = make(map[int]struct {
			result1 *webrtc.Peer
			result2 error
		})
	}
	fake.acceptOfferReturnsOnCall[i] = struct {
		result1 *webrtc.Peer
		result2 error
	}{result1, result2}
}

func (fake *FakePeerConnectionFactory) ApplyAnswer(arg1 context.Context, arg2 *webrtc.PeerOffer, arg3 string) (*webrtc.Peer, error) {
	fake.applyAnswerMutex.Lock()
	ret, specificReturn := fake.applyAnswerReturnsOnCall[len(fake.applyAnswerArgsForCall)]
	fake.applyAnswerArgsForCall = append(fake.applyAnswerArgsForCall, struct {
		arg1 context.Context
		arg2 *webrtc.PeerOffer
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ApplyAnswerStub
	fakeReturns := fake.applyAnswerReturns
	fake.recordInvocation("ApplyAnswer", []interface{}{arg1, arg2, arg3})
	fake.applyAnswerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePeerConnectionFactory) ApplyAnswerCallCount() int {
	fake.applyAnswerMutex.RLock()
	defer fake.applyAnswerMutex.RUnlock()
	return len(fake.applyAnswerArgsForCall)
}

func (fake *FakePeerConnectionFactory) ApplyAnswerCalls(stub func(context.Context, *webrtc.PeerOffer, string) (*webrtc.Peer, error)) {
	fake.applyAnswerMutex.Lock()
	defer fake.applyAnswerMutex.Unlock()
	fake.ApplyAnswerStub = stub
}

func (fake *FakePeerConnectionFactory) ApplyAnswerArgsForCall(i int) (context.Context, *webrtc.PeerOffer, string) {
	fake.applyAnswerMutex.RLock()
	defer fake.applyAnswerMutex.RUnlock()
	argsForCall := fake.applyAnswerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePeerConnectionFactory) ApplyAnswerReturns(result1 *webrtc.Peer, result2 error) {
	fake.applyAnswerMutex.Lock()
	defer fake.applyAnswerMutex.Unlock()
	fake.ApplyAnswerStub = nil
	fake.applyAnswerReturns = struct {
		result1 *webrtc.Peer
		result2 error
	}{result1, result2}
}

func (fake *FakePeerConnectionFactory) ApplyAnswerReturnsOnCall(i int, result1 *webrtc.Peer, result2 error) {
	fake.applyAnswerMutex.Lock()
	defer fake.applyAnswerMutex.Unlock()
	fake.ApplyAnswerStub = nil
	if fake.applyAnswerReturnsOnCall == nil {
		fake.applyAnswerReturnsOnCall = make(map[int]struct {
			result1 *webrtc.Peer
			result2 error
		})
	}
	fake.applyAnswerReturnsOnCall[i] = struct {
		result1 *webrtc.Peer
		result2 error
	}{result1, result2}
}

func (fake *FakePeerConnectionFactory) CloseParticipant(arg1 context.Context, arg2 vo.SessionID, arg3 vo.ParticipantID) error {
	fake.closeParticipantMutex.Lock()
	ret, specificReturn := fake.closeParticipantReturnsOnCall[len(fake.closeParticipantArgsForCall)]
	fake.closeParticipantArgsForCall = append(fake.closeParticipantArgsForCall, struct {
		arg1 context.Context
		arg2 vo.SessionID
		arg3 vo.ParticipantID
	}{arg1, arg2, arg3})
	stub := fake.CloseParticipantStub
	fakeReturns := fake.closeParticipantReturns
	fake.recordInvocation("CloseParticipant", []interface{}{arg1, arg2, arg3})
	fake.closeParticipantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePeerConnectionFactory) CloseParticipantCallCount() int {
	fake.closeParticipantMutex.RLock()
	defer fake.closeParticipantMutex.RUnlock()
	return len(fake.closeParticipantArgsForCall)
}

func (fake *FakePeerConnectionFactory) CloseParticipantCalls(stub func(context.Context, vo.SessionID, vo.ParticipantID) error) {
	fake.closeParticipantMutex.Lock()
	defer fake.closeParticipantMutex.Unlock()
	fake.CloseParticipantStub = stub
}

func (fake *FakePeerConnectionFactory) CloseParticipantArgsForCall(i int) (context.Context, vo.SessionID, vo.ParticipantID) {
	fake.closeParticipantMutex.RLock()
	defer fake.closeParticipantMutex.RUnlock()
	argsForCall := fake.closeParticipantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePeerConnectionFactory) CloseParticipantReturns(result1 error) {
	fake.closeParticipantMutex.Lock()
	defer fake.closeParticipantMutex.Unlock()
	fake.CloseParticipantStub = nil
	fake.closeParticipantReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePeerConnectionFactory) CloseParticipantReturnsOnCall(i int, result1 error) {
	fake.closeParticipantMutex.Lock()
	defer fake.closeParticipantMutex.Unlock()
	fake.CloseParticipantStub = nil
	if fake.closeParticipantReturnsOnCall == nil {
		fake.closeParticipantReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeParticipantReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePeerConnectionFactory) CloseSession(arg1 context.Context, arg2 vo.SessionID) error {
	fake.closeSessionMutex.Lock()
	ret, specificReturn := fake.closeSessionReturnsOnCall[len(fake.closeSessionArgsForCall)]
	fake.closeSessionArgsForCall = append(fake.closeSessionArgsForCall, struct {
		arg1 context.Context
		arg2 vo.SessionID
	}{arg1, arg2})
	stub := fake.CloseSessionStub
	fakeReturns := fake.closeSessionReturns
	fake.recordInvocation("CloseSession", []interface{}{arg1, arg2})
	fake.closeSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePeerConnectionFactory) CloseSessionCallCount() int {
	fake.closeSessionMutex.RLock()
	defer fake.closeSessionMutex.RUnlock()
	return len(fake.closeSessionArgsForCall)
}

func (fake *FakePeerConnectionFactory) CloseSessionCalls(stub func(context.Context, vo.SessionID) error) {
	fake.closeSessionMutex.Lock()
	defer fake.closeSessionMutex.Unlock()
	fake.CloseSessionStub = stub
}

func (fake *FakePeerConnectionFactory) CloseSessionArgsForCall(i int) (context.Context, vo.SessionID) {
	fake.closeSessionMutex.RLock()
	defer fake.closeSessionMutex.RUnlock()
	argsForCall := fake.closeSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePeerConnectionFactory) CloseSessionReturns(result1 error) {
	fake.closeSessionMutex.Lock()
	defer fake.closeSessionMutex.Unlock()
	fake.CloseSessionStub = nil
	fake.closeSessionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePeerConnectionFactory) CloseSessionReturnsOnCall(i int, result1 error) {
	fake.closeSessionMutex.Lock()
	defer fake.closeSessionMutex.Unlock()
	fake.CloseSessionStub = nil
	if fake.closeSessionReturnsOnCall == nil {
		fake.closeSessionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeSessionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePeerConnectionFactory) CreateOffer(arg1 context.Context, arg2 webrtc.CreateOfferInput) (*webrtc.PeerOffer, error) {
	fake.createOfferMutex.Lock()
	ret, specificReturn := fake.createOfferReturnsOnCall[len(fake.createOfferArgsForCall)]
	fake.createOfferArgsForCall = append(fake.createOfferArgsForCall, struct {
		arg1 context.Context
		arg2 webrtc.CreateOfferInput
	}{arg1, arg2})
	stub := fake.CreateOfferStub
	fakeReturns := fake.createOfferReturns
	fake.recordInvocation("CreateOffer", []interface{}{arg1, arg2})
	fake.createOfferMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePeerConnectionFactory) CreateOfferCallCount() int {
	fake.createOfferMutex.RLock()
	defer fake.createOfferMutex.RUnlock()
	return len(fake.createOfferArgsForCall)
}

func (fake *FakePeerConnectionFactory) CreateOfferCalls(stub func(context.Context, webrtc.CreateOfferInput) (*webrtc.PeerOffer, error)) {
	fake.createOfferMutex.Lock()
	defer fake.createOfferMutex.Unlock()
	fake.CreateOfferStub = stub
}

func (fake *FakePeerConnectionFactory) CreateOfferArgsForCall(i int) (context.Context, webrtc.CreateOfferInput) {
	fake.createOfferMutex.RLock()
	defer fake.createOfferMutex.RUnlock()
	argsForCall := fake.createOfferArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePeerConnectionFactory) CreateOfferReturns(result1 *webrtc.PeerOffer, result2 error) {
	fake.createOfferMutex.Lock()
	defer fake.createOfferMutex.Unlock()
	fake.CreateOfferStub = nil
	fake.createOfferReturns = struct {
		result1 *webrtc.PeerOffer
		result2 error
	}{result1, result2}
}

func (fake *FakePeerConnectionFactory) CreateOfferReturnsOnCall(i int, result1 *webrtc.PeerOffer, result2 error) {
	fake.createOfferMutex.Lock()
	defer fake.createOfferMutex.Unlock()
	fake.CreateOfferStub = nil
	if fake.createOfferReturnsOnCall == nil {
		fake.createOfferReturnsOnCall = make(map[int]struct {
			result1 *webrtc.PeerOffer
			result2 error
		})
	}
	fake.createOfferReturnsOnCall[i] = struct {
		result1 *webrtc.PeerOffer
		result2 error
	}{result1, result2}
}

func (fake *FakePeerConnectionFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePeerConnectionFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ webrtc.PeerConnectionFactory = new(FakePeerConnectionFactory)
