// Code generated by counterfeiter. DO NOT EDIT.
package webrtcfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/pkg/webrtc"
)

type FakeOfferCreator struct {
	CreateOfferStub        func(context.Context, webrtc.CreateOfferInput) (*webrtc.PeerOffer, error)
	createOfferMutex       sync.RWMutex
	createOfferArgsForCall []struct {
		arg1 context.Context
		arg2 webrtc.CreateOfferInput
	}
	createOfferReturns struct {
		result1 *webrtc.PeerOffer
		result2 error
	}
	createOfferReturnsOnCall map[int]struct {
		result1 *webrtc.PeerOffer
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOfferCreator) CreateOffer(arg1 context.Context, arg2 webrtc.CreateOfferInput) (*webrtc.PeerOffer, error) {
	fake.createOfferMutex.Lock()
	ret, specificReturn := fake.createOfferReturnsOnCall[len(fake.createOfferArgsForCall)]
	fake.createOfferArgsForCall = append(fake.createOfferArgsForCall, struct {
		arg1 context.Context
		arg2 webrtc.CreateOfferInput
	}{arg1, arg2})
	stub := fake.CreateOfferStub
	fakeReturns := fake.createOfferReturns
	fake.recordInvocation("CreateOffer", []interface{}{arg1, arg2})
	fake.createOfferMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOfferCreator) CreateOfferCallCount() int {
	fake.createOfferMutex.RLock()
	defer fake.createOfferMutex.RUnlock()
	return len(fake.createOfferArgsForCall)
}

func (fake *FakeOfferCreator) CreateOfferCalls(stub func(context.Context, webrtc.CreateOfferInput) (*webrtc.PeerOffer, error)) {
	fake.createOfferMutex.Lock()
	defer fake.createOfferMutex.Unlock()
	fake.CreateOfferStub = stub
}

func (fake *FakeOfferCreator) CreateOfferArgsForCall(i int) (context.Context, webrtc.CreateOfferInput) {
	fake.createOfferMutex.RLock()
	defer fake.createOfferMutex.RUnlock()
	argsForCall := fake.createOfferArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOfferCreator) CreateOfferReturns(result1 *webrtc.PeerOffer, result2 error) {
	fake.createOfferMutex.Lock()
	defer fake.createOfferMutex.Unlock()
	fake.CreateOfferStub = nil
	fake.createOfferReturns = struct {
		result1 *webrtc.PeerOffer
		result2 error
	}{result1, result2}
}

func (fake *FakeOfferCreator) CreateOfferReturnsOnCall(i int, result1 *webrtc.PeerOffer, result2 error) {
	fake.createOfferMutex.Lock()
	defer fake.createOfferMutex.Unlock()
	fake.CreateOfferStub = nil
	if fake.createOfferReturnsOnCall == nil {
		fake.createOfferReturnsOnCall = make(map[int]struct {
			result1 *webrtc.PeerOffer
			result2 error
		})
	}
	fake.createOfferReturnsOnCall[i] = struct {
		result1 *webrtc.PeerOffer
		result2 error
	}{result1, result2}
}

func (fake *FakeOfferCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOfferCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ webrtc.OfferCreator = new(FakeOfferCreator)
