// Code generated by counterfeiter. DO NOT EDIT.
package webrtcfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/portfoilo-media/internal/pkg/webrtc"
)

type FakeAnswerApplier struct {
	ApplyAnswerStub        func(context.Context, *webrtc.PeerOffer, string) (*webrtc.Peer, error)
	applyAnswerMutex       sync.RWMutex
	applyAnswerArgsForCall []struct {
		arg1 context.Context
		arg2 *webrtc.PeerOffer
		arg3 string
	}
	applyAnswerReturns struct {
		result1 *webrtc.Peer
		result2 error
	}
	applyAnswerReturnsOnCall map[int]struct {
		result1 *webrtc.Peer
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAnswerApplier) ApplyAnswer(arg1 context.Context, arg2 *webrtc.PeerOffer, arg3 string) (*webrtc.Peer, error) {
	fake.applyAnswerMutex.Lock()
	ret, specificReturn := fake.applyAnswerReturnsOnCall[len(fake.applyAnswerArgsForCall)]
	fake.applyAnswerArgsForCall = append(fake.applyAnswerArgsForCall, struct {
		arg1 context.Context
		arg2 *webrtc.PeerOffer
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ApplyAnswerStub
	fakeReturns := fake.applyAnswerReturns
	fake.recordInvocation("ApplyAnswer", []interface{}{arg1, arg2, arg3})
	fake.applyAnswerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAnswerApplier) ApplyAnswerCallCount() int {
	fake.applyAnswerMutex.RLock()
	defer fake.applyAnswerMutex.RUnlock()
	return len(fake.applyAnswerArgsForCall)
}

func (fake *FakeAnswerApplier) ApplyAnswerCalls(stub func(context.Context, *webrtc.PeerOffer, string) (*webrtc.Peer, error)) {
	fake.applyAnswerMutex.Lock()
	defer fake.applyAnswerMutex.Unlock()
	fake.ApplyAnswerStub = stub
}

func (fake *FakeAnswerApplier) ApplyAnswerArgsForCall(i int) (context.Context, *webrtc.PeerOffer, string) {
	fake.applyAnswerMutex.RLock()
	defer fake.applyAnswerMutex.RUnlock()
	argsForCall := fake.applyAnswerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAnswerApplier) ApplyAnswerReturns(result1 *webrtc.Peer, result2 error) {
	fake.applyAnswerMutex.Lock()
	defer fake.applyAnswerMutex.Unlock()
	fake.ApplyAnswerStub = nil
	fake.applyAnswerReturns = struct {
		result1 *webrtc.Peer
		result2 error
	}{result1, result2}
}

func (fake *FakeAnswerApplier) ApplyAnswerReturnsOnCall(i int, result1 *webrtc.Peer, result2 error) {
	fake.applyAnswerMutex.Lock()
	defer fake.applyAnswerMutex.Unlock()
	fake.ApplyAnswerStub = nil
	if fake.applyAnswerReturnsOnCall == nil {
		fake.applyAnswerReturnsOnCall = make(map[int]struct {
			result1 *webrtc.Peer
			result2 error
		})
	}
	fake.applyAnswerReturnsOnCall[i] = struct {
		result1 *webrtc.Peer
		result2 error
	}{result1, result2}
}

func (fake *FakeAnswerApplier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAnswerApplier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ webrtc.AnswerApplier = new(FakeAnswerApplier)
